import type {
  Brand, CarModel, Car, Company, Booking, Contract, PricingTier, Transaction,
  ChargingCost, Invoice, RentToSellEntry, AppNotification, AdminUser,
  Location, ConnectorType, RentRequest, TelematicsVehicle, TripRecord, BehaviorEvent, PurchaseOffer,
} from "./types";

// ─── Brands ───────────────────────────────────────────────────────────────────
export const brands: Brand[] = [
  { id: "b1", name: "JAC" },
];

// ─── Models ───────────────────────────────────────────────────────────────────
export const carModels: CarModel[] = [
  {
    id: "m1", brandId: "b1", brandName: "JAC", name: "N55 EV",
    year: 2024, batteryKwh: 82, rangeWltp: 210, rangeNedc: 230,
    connectors: ["CCS2", "GB/T"] as ConnectorType[],
    maxAcKw: 7, maxDcKw: 60,
    photos: ["http://jacen.jac.com.cn/_nuxt/img/n55ev.5eb6f0b.png"],
    highlights: ["Payload 1,080 kg", "Single Cab", "LED Headlights", "Fleet Telematics Ready"],
    priceFrom: 25000,
  },
  {
    id: "m2", brandId: "b1", brandName: "JAC", name: "T9 EV",
    year: 2024, batteryKwh: 120, rangeWltp: 260, rangeNedc: 290,
    connectors: ["CCS2", "GB/T"] as ConnectorType[],
    maxAcKw: 11, maxDcKw: 90,
    photos: ["http://jacen.jac.com.cn/_nuxt/img/t9ev.d5fb6be.png"],
    highlights: ["Payload 1,500 kg", "Dual Cab", "Hill Descent Control", "6-Seat Cab"],
    priceFrom: 38000,
  },
  {
    id: "m3", brandId: "b1", brandName: "JAC", name: "Sunray EV",
    year: 2024, batteryKwh: 60, rangeWltp: 300, rangeNedc: 330,
    connectors: ["CCS2", "GB/T"] as ConnectorType[],
    maxAcKw: 7, maxDcKw: 40,
    photos: ["http://jacen.jac.com.cn/_nuxt/img/sunrayEv.d4abd52.png"],
    highlights: ["15-Seat Van", "Sliding Door", "Roof AC", "Cargo Variant Available"],
    priceFrom: 28000,
  },
  {
    id: "m4", brandId: "b1", brandName: "JAC", name: "M3 EV",
    year: 2024, batteryKwh: 75, rangeWltp: 250, rangeNedc: 275,
    connectors: ["CCS2", "GB/T"] as ConnectorType[],
    maxAcKw: 7, maxDcKw: 60,
    photos: ["http://jacen.jac.com.cn/_nuxt/img/m3ev.8830ba3.png"],
    highlights: ["Payload 1,200 kg", "Flatbed", "Tow Hitch", "Rear Camera"],
    priceFrom: 27000,
  },
  {
    id: "m5", brandId: "b1", brandName: "JAC", name: "N-Series", bodyType: "Cargo",
    year: 2024, batteryKwh: 100, rangeWltp: 200, rangeNedc: 220,
    connectors: ["CCS2", "GB/T"] as ConnectorType[],
    maxAcKw: 11, maxDcKw: 80,
    photos: ["http://jacen.jac.com.cn/_nuxt/img/n-series.442957a.png"],
    highlights: ["10-Ton GVW", "Enclosed Box Body", "Tail Lift Option", "Cold Chain Ready"],
    priceFrom: 35000,
  },
  {
    id: "m6", brandId: "b1", brandName: "JAC", name: "N-Series", bodyType: "Dump Truck",
    year: 2024, batteryKwh: 100, rangeWltp: 190, rangeNedc: 210,
    connectors: ["CCS2", "GB/T"] as ConnectorType[],
    maxAcKw: 11, maxDcKw: 80,
    photos: ["http://jacen.jac.com.cn/_nuxt/img/n-series.442957a.png"],
    highlights: ["10-Ton GVW", "Hydraulic Tipper", "3-Way Dump", "Reinforced Chassis"],
    priceFrom: 38000,
  },
  {
    id: "m7", brandId: "b1", brandName: "JAC", name: "N-Series", bodyType: "Sweeper",
    year: 2024, batteryKwh: 100, rangeWltp: 180, rangeNedc: 200,
    connectors: ["CCS2", "GB/T"] as ConnectorType[],
    maxAcKw: 11, maxDcKw: 80,
    photos: ["http://jacen.jac.com.cn/_nuxt/img/n-series.442957a.png"],
    highlights: ["Road Sweeper Body", "Water Tank 4,000L", "Brush Width 2.8m", "Dust Suppression System"],
    priceFrom: 40000,
  },
  {
    id: "m8", brandId: "b1", brandName: "JAC", name: "N-Series", bodyType: "Wrecker",
    year: 2024, batteryKwh: 100, rangeWltp: 185, rangeNedc: 205,
    connectors: ["CCS2", "GB/T"] as ConnectorType[],
    maxAcKw: 11, maxDcKw: 80,
    photos: ["http://jacen.jac.com.cn/_nuxt/img/n-series.442957a.png"],
    highlights: ["10-Ton GVW", "Rotary Tow Crane", "Flatbed Recovery", "Hydraulic Lift"],
    priceFrom: 42000,
  },
  {
    id: "m9", brandId: "b1", brandName: "JAC", name: "N-Series", bodyType: "Fridge",
    year: 2024, batteryKwh: 100, rangeWltp: 195, rangeNedc: 215,
    connectors: ["CCS2", "GB/T"] as ConnectorType[],
    maxAcKw: 11, maxDcKw: 80,
    photos: ["http://jacen.jac.com.cn/_nuxt/img/n-series.442957a.png"],
    highlights: ["Refrigeration Unit -20°C", "Insulated Box Body", "Temperature Logger", "Side Door"],
    priceFrom: 40000,
  },
  {
    id: "m10", brandId: "b1", brandName: "JAC", name: "N-Series", bodyType: "Sewage",
    year: 2024, batteryKwh: 100, rangeWltp: 175, rangeNedc: 195,
    connectors: ["CCS2", "GB/T"] as ConnectorType[],
    maxAcKw: 11, maxDcKw: 80,
    photos: ["http://jacen.jac.com.cn/_nuxt/img/n-series.442957a.png"],
    highlights: ["Tank 6,000L", "High-Pressure Suction Pump", "Reel Hose 20m", "Deodorizer System"],
    priceFrom: 43000,
  },
  {
    id: "m11", brandId: "b1", brandName: "JAC", name: "K7",
    year: 2024, batteryKwh: 150, rangeWltp: 230, rangeNedc: 260,
    connectors: ["CCS2", "GB/T"] as ConnectorType[],
    maxAcKw: 11, maxDcKw: 120,
    photos: ["http://jacen.jac.com.cn/_nuxt/img/k7.f1cc20e.png"],
    highlights: ["18-Ton GVW", "Semi-Trailer Tractor", "Sleep Cab", "Adaptive Cruise"],
    priceFrom: 50000,
  },
  {
    id: "m12", brandId: "b1", brandName: "JAC", name: "K3",
    year: 2024, batteryKwh: 90, rangeWltp: 220, rangeNedc: 245,
    connectors: ["CCS2", "GB/T"] as ConnectorType[],
    maxAcKw: 11, maxDcKw: 80,
    photos: ["http://jacen.jac.com.cn/_nuxt/img/K3.fb32588.png"],
    highlights: ["8-Ton GVW", "Day Cab", "Lane Keep Assist", "Electronic Brake System"],
    priceFrom: 35000,
  },
  {
    id: "m13", brandId: "b1", brandName: "JAC", name: "Q7",
    year: 2024, batteryKwh: 180, rangeWltp: 260, rangeNedc: 290,
    connectors: ["CCS2", "GB/T"] as ConnectorType[],
    maxAcKw: 11, maxDcKw: 150,
    photos: ["http://jacen.jac.com.cn/_nuxt/img/Q7.c13fa4b.png"],
    highlights: ["25-Ton GVW", "Heavy Tractor", "8x4 Drive", "Air Suspension"],
    priceFrom: 55000,
  },
  {
    id: "m14", brandId: "b1", brandName: "JAC", name: "X-Series",
    year: 2024, batteryKwh: 200, rangeWltp: 280, rangeNedc: 310,
    connectors: ["CCS2", "GB/T"] as ConnectorType[],
    maxAcKw: 11, maxDcKw: 180,
    photos: ["http://jacen.jac.com.cn/_nuxt/img/x-series.f7735ae.png"],
    highlights: ["30-Ton GVW", "Heavy Hauler", "Sleeper Cab", "Smart Safety Suite"],
    priceFrom: 65000,
  },
  {
    id: "m15", brandId: "b1", brandName: "JAC", name: "SPV",
    year: 2024, batteryKwh: 120, rangeWltp: 220, rangeNedc: 250,
    connectors: ["CCS2", "GB/T"] as ConnectorType[],
    maxAcKw: 11, maxDcKw: 100,
    photos: ["http://jacen.jac.com.cn/_nuxt/img/specialPurpose Truck.3820d53.png"],
    highlights: ["Special Purpose Body", "Custom Outfitting", "Multiple Configurations", "Command Unit Option"],
    priceFrom: 60000,
  },
];

// ─── Locations ─────────────────────────────────────────────────────────────────
export const locations: Location[] = [
  { id: "l1", name: "Sukhumvit Service Center", address: "123 Sukhumvit Rd, Khlong Toei, Bangkok 10110" },
  { id: "l2", name: "Silom Office Hub", address: "45 Silom Rd, Bang Rak, Bangkok 10500" },
  { id: "l3", name: "Ladkrabang Depot", address: "88 Chalerm Mahanakorn Rd, Lat Krabang, Bangkok 10520" },
  { id: "l4", name: "Don Mueang Station", address: "222 Vibhavadi Rangsit Rd, Don Mueang, Bangkok 10210" },
  { id: "l5", name: "Rama 9 Headquarters", address: "9 Rama 9 Rd, Huai Khwang, Bangkok 10310" },
];

// ─── Companies ────────────────────────────────────────────────────────────────
export const companies: Company[] = [
  {
    id: "c1", name: "Siam Motors Group", taxId: "0105562123456",
    address: "1 Wireless Rd, Lumpini, Bangkok 10330",
    billingEmail: "billing@siammotors.co.th",
    contactName: "Natthapong Charoenwong", contactPhone: "02-123-4567",
    contactEmail: "natthapong@siammotors.co.th",
    kycStatus: "Verified",
    kycDocuments: [
      { name: "Business Registration Certificate", uploadedAt: "2025-11-10", type: "PDF" },
      { name: "VAT Registration", uploadedAt: "2025-11-10", type: "PDF" },
      { name: "Director ID Card", uploadedAt: "2025-11-10", type: "Image" },
    ],
    users: [
      { id: "u1", name: "Natthapong Charoenwong", email: "natthapong@siammotors.co.th", role: "Renter Admin", lastActive: "2026-05-14" },
      { id: "u2", name: "Siriporn Wiriyakul", email: "siriporn@siammotors.co.th", role: "Renter User", lastActive: "2026-05-13" },
    ],
    creditLimit: 500000, maxActiveRentals: 10, activeRentals: 4, status: "Active",
  },
  {
    id: "c2", name: "Bangkok Fleet Solutions", taxId: "0105563234567",
    address: "200 Ratchadapisek Rd, Huai Khwang, Bangkok 10310",
    billingEmail: "accounts@bkkfleet.co.th",
    contactName: "Thanakorn Pattanapong", contactPhone: "02-234-5678",
    contactEmail: "thanakorn@bkkfleet.co.th",
    kycStatus: "Verified",
    kycDocuments: [
      { name: "Business Registration Certificate", uploadedAt: "2025-10-05", type: "PDF" },
      { name: "Bank Statement", uploadedAt: "2025-10-05", type: "PDF" },
    ],
    users: [
      { id: "u3", name: "Thanakorn Pattanapong", email: "thanakorn@bkkfleet.co.th", role: "Renter Admin", lastActive: "2026-05-15" },
    ],
    creditLimit: 300000, maxActiveRentals: 6, activeRentals: 2, status: "Active",
  },
  {
    id: "c3", name: "ThaiBev Logistics", taxId: "0105564345678",
    address: "14 Vibhavadi Rangsit Rd, Chatuchak, Bangkok 10900",
    billingEmail: "finance@thaibevlogistics.co.th",
    contactName: "Ananya Sukhonthamat", contactPhone: "02-345-6789",
    contactEmail: "ananya@thaibevlogistics.co.th",
    kycStatus: "Pending",
    kycDocuments: [
      { name: "Business Registration Certificate", uploadedAt: "2026-04-20", type: "PDF" },
    ],
    users: [
      { id: "u4", name: "Ananya Sukhonthamat", email: "ananya@thaibevlogistics.co.th", role: "Renter Admin", lastActive: "2026-05-10" },
    ],
    creditLimit: 200000, maxActiveRentals: 4, activeRentals: 1, status: "Active",
  },
  {
    id: "c4", name: "PTT Mobility Co.", taxId: "0105565456789",
    address: "555 Vibhavadi Rangsit Rd, Chatuchak, Bangkok 10900",
    billingEmail: "billing@pttmobility.co.th",
    contactName: "Siriporn Wiriyakul", contactPhone: "02-456-7890",
    contactEmail: "siriporn@pttmobility.co.th",
    kycStatus: "Verified",
    kycDocuments: [
      { name: "Business Registration Certificate", uploadedAt: "2025-09-15", type: "PDF" },
      { name: "Company Affidavit", uploadedAt: "2025-09-15", type: "PDF" },
    ],
    users: [
      { id: "u5", name: "Siriporn Wiriyakul", email: "siriporn@pttmobility.co.th", role: "Renter Admin", lastActive: "2026-05-12" },
      { id: "u6", name: "Kittipong Sangsuk", email: "kittipong@pttmobility.co.th", role: "Renter User", lastActive: "2026-05-08" },
    ],
    creditLimit: 800000, maxActiveRentals: 15, activeRentals: 5, status: "Active",
  },
  {
    id: "c5", name: "Central Retail Transport", taxId: "0105566567890",
    address: "306 Silom Rd, Suriyawong, Bang Rak, Bangkok 10500",
    billingEmail: "transport@central.co.th",
    contactName: "Thanakorn Pattanapong", contactPhone: "02-567-8901",
    contactEmail: "thanakorn.p@central.co.th",
    kycStatus: "Rejected",
    kycDocuments: [
      { name: "Business Registration Certificate", uploadedAt: "2026-03-10", type: "PDF" },
    ],
    users: [
      { id: "u7", name: "Thanakorn Pattanapong", email: "thanakorn.p@central.co.th", role: "Renter Admin", lastActive: "2026-03-20" },
    ],
    creditLimit: 0, maxActiveRentals: 0, activeRentals: 0, status: "Inactive",
  },
];

// ─── Cars ─────────────────────────────────────────────────────────────────────
export const cars: Car[] = [
  {
    id: "car1", licensePlate: "กก 1234 กทม", modelId: "m1", brandName: "JAC", modelName: "N55 EV",
    year: 2024, color: "White", status: "Rented", rfidCard: "RFID-JAC-001",
    currentRenterId: "c1", currentRenterName: "Siam Motors Group", currentBookingId: "bk1",
    odometer: 12450, isRentToSell: true,
    statusHistory: [
      { status: "Available", date: "2025-12-01", changedBy: "Natthapong Charoenwong" },
      { status: "Rented", date: "2026-02-01", changedBy: "System", note: "Booking BK-001" },
    ],
    maintenanceLogs: [
      { id: "ml1", date: "2026-01-15", type: "Battery Check", cost: 2500, provider: "JAC Service Center", notes: "Battery health 98%, all good" },
    ],
    insurance: { policyNumber: "INS-2024-001", provider: "AXA Insurance", expiryDate: "2026-12-31", annualPremium: 32000 },
    odometerLogs: [
      { date: "2025-12-01", reading: 0 },
      { date: "2026-02-01", reading: 3200, bookingId: "bk1" },
      { date: "2026-05-01", reading: 12450 },
    ],
  },
  {
    id: "car2", licensePlate: "ขข 5678 กทม", modelId: "m1", brandName: "JAC", modelName: "N55 EV",
    year: 2024, color: "Silver", status: "Available", rfidCard: "RFID-JAC-002",
    odometer: 4300, isRentToSell: false,
    statusHistory: [
      { status: "Available", date: "2025-11-15", changedBy: "System" },
    ],
    maintenanceLogs: [],
    insurance: { policyNumber: "INS-2024-002", provider: "AXA Insurance", expiryDate: "2026-12-31", annualPremium: 32000 },
    odometerLogs: [{ date: "2025-11-15", reading: 0 }],
  },
  {
    id: "car3", licensePlate: "คค 9012 กทม", modelId: "m2", brandName: "JAC", modelName: "T9 EV",
    year: 2024, color: "White", status: "Rented", rfidCard: "RFID-JAC-003",
    currentRenterId: "c2", currentRenterName: "Bangkok Fleet Solutions", currentBookingId: "bk2",
    odometer: 9800, isRentToSell: false,
    statusHistory: [
      { status: "Available", date: "2025-10-20", changedBy: "System" },
      { status: "Rented", date: "2026-03-01", changedBy: "System", note: "Booking BK-002" },
    ],
    maintenanceLogs: [
      { id: "ml2", date: "2025-12-10", type: "Annual Service", cost: 5500, provider: "JAC Authorized Service", notes: "Full annual inspection completed" },
    ],
    insurance: { policyNumber: "INS-2024-003", provider: "Dhipaya Insurance", expiryDate: "2026-10-31", annualPremium: 45000 },
    odometerLogs: [{ date: "2025-10-20", reading: 0 }, { date: "2026-03-01", reading: 5000 }],
  },
  {
    id: "car4", licensePlate: "งง 3456 กทม", modelId: "m2", brandName: "JAC", modelName: "T9 EV",
    year: 2024, color: "Blue", status: "Maintenance", rfidCard: "RFID-JAC-004",
    odometer: 21000, isRentToSell: false,
    statusHistory: [
      { status: "Available", date: "2025-08-01", changedBy: "System" },
      { status: "Rented", date: "2025-10-01", changedBy: "System" },
      { status: "Available", date: "2026-01-01", changedBy: "System" },
      { status: "Maintenance", date: "2026-04-01", changedBy: "Thanakorn Pattanapong", note: "Drive motor check required" },
    ],
    maintenanceLogs: [
      { id: "ml3", date: "2026-04-01", type: "Motor Diagnostic", cost: 8000, provider: "JAC Authorized Service", notes: "Drive motor inspection in progress" },
    ],
    insurance: { policyNumber: "INS-2024-004", provider: "Dhipaya Insurance", expiryDate: "2026-10-31", annualPremium: 45000 },
    odometerLogs: [{ date: "2025-08-01", reading: 0 }, { date: "2026-04-01", reading: 21000 }],
  },
  {
    id: "car5", licensePlate: "จจ 7890 กทม", modelId: "m5", brandName: "JAC", modelName: "N-Series", bodyType: "Cargo",
    year: 2024, color: "White", status: "Rented", rfidCard: "RFID-JAC-005",
    currentRenterId: "c1", currentRenterName: "Siam Motors Group", currentBookingId: "bk3",
    odometer: 35200, isRentToSell: true,
    statusHistory: [
      { status: "Available", date: "2025-06-01", changedBy: "System" },
      { status: "Rented", date: "2025-08-01", changedBy: "System" },
    ],
    maintenanceLogs: [
      { id: "ml4", date: "2025-12-15", type: "Brake Inspection", cost: 3500, provider: "JAC Service Center", notes: "Brake pads replaced" },
      { id: "ml5", date: "2026-03-20", type: "Tire Replacement", cost: 12000, provider: "JAC Service Center", notes: "4 tires replaced" },
    ],
    insurance: { policyNumber: "INS-2023-001", provider: "Viriyah Insurance", expiryDate: "2026-07-31", annualPremium: 38000 },
    odometerLogs: [{ date: "2025-06-01", reading: 8000 }, { date: "2026-05-01", reading: 35200 }],
  },
  {
    id: "car6", licensePlate: "ฉฉ 1234 กทม", modelId: "m6", brandName: "JAC", modelName: "N-Series", bodyType: "Dump Truck",
    year: 2024, color: "Yellow", status: "Available", rfidCard: "RFID-JAC-006",
    odometer: 18500, isRentToSell: false,
    statusHistory: [
      { status: "Available", date: "2025-07-01", changedBy: "System" },
      { status: "Rented", date: "2025-09-01", changedBy: "System" },
      { status: "Available", date: "2026-02-15", changedBy: "System" },
    ],
    maintenanceLogs: [],
    insurance: { policyNumber: "INS-2023-002", provider: "Viriyah Insurance", expiryDate: "2026-07-31", annualPremium: 40000 },
    odometerLogs: [{ date: "2025-07-01", reading: 5000 }],
  },
  {
    id: "car7", licensePlate: "ชช 5678 กทม", modelId: "m11", brandName: "JAC", modelName: "K7",
    year: 2024, color: "White", status: "Rented", rfidCard: "RFID-JAC-007",
    currentRenterId: "c4", currentRenterName: "PTT Mobility Co.", currentBookingId: "bk4",
    odometer: 6700, isRentToSell: false,
    statusHistory: [
      { status: "Available", date: "2026-01-10", changedBy: "System" },
      { status: "Rented", date: "2026-04-01", changedBy: "System" },
    ],
    maintenanceLogs: [],
    insurance: { policyNumber: "INS-2024-005", provider: "LMG Insurance", expiryDate: "2027-01-31", annualPremium: 55000 },
    odometerLogs: [{ date: "2026-01-10", reading: 0 }],
  },
  {
    id: "car8", licensePlate: "ซซ 9012 กทม", modelId: "m12", brandName: "JAC", modelName: "K3",
    year: 2024, color: "White", status: "Available", rfidCard: "RFID-JAC-008",
    odometer: 2100, isRentToSell: false,
    statusHistory: [
      { status: "Available", date: "2026-02-01", changedBy: "System" },
    ],
    maintenanceLogs: [],
    insurance: { policyNumber: "INS-2024-006", provider: "LMG Insurance", expiryDate: "2027-01-31", annualPremium: 38000 },
    odometerLogs: [{ date: "2026-02-01", reading: 0 }],
  },
  {
    id: "car9", licensePlate: "ญญ 3456 กทม", modelId: "m3", brandName: "JAC", modelName: "Sunray EV",
    year: 2024, color: "White", status: "Rented", rfidCard: "RFID-JAC-009",
    currentRenterId: "c3", currentRenterName: "ThaiBev Logistics", currentBookingId: "bk5",
    odometer: 9400, isRentToSell: false,
    statusHistory: [
      { status: "Available", date: "2025-12-20", changedBy: "System" },
      { status: "Rented", date: "2026-03-15", changedBy: "System" },
    ],
    maintenanceLogs: [],
    insurance: { policyNumber: "INS-2024-007", provider: "AXA Insurance", expiryDate: "2026-12-31", annualPremium: 30000 },
    odometerLogs: [{ date: "2025-12-20", reading: 0 }],
  },
  {
    id: "car10", licensePlate: "ฎฎ 7890 กทม", modelId: "m4", brandName: "JAC", modelName: "M3 EV",
    year: 2024, color: "Grey", status: "Available", rfidCard: "RFID-JAC-010",
    odometer: 3200, isRentToSell: false,
    statusHistory: [
      { status: "Available", date: "2026-01-05", changedBy: "System" },
    ],
    maintenanceLogs: [],
    insurance: { policyNumber: "INS-2024-008", provider: "AXA Insurance", expiryDate: "2026-12-31", annualPremium: 30000 },
    odometerLogs: [{ date: "2026-01-05", reading: 0 }],
  },
  {
    id: "car11", licensePlate: "ฏฏ 1111 กทม", modelId: "m13", brandName: "JAC", modelName: "Q7",
    year: 2023, color: "White", status: "Sold", rfidCard: "RFID-JAC-011",
    odometer: 48000, isRentToSell: false,
    statusHistory: [
      { status: "Available", date: "2024-01-01", changedBy: "System" },
      { status: "Rented", date: "2024-03-01", changedBy: "System" },
      { status: "Sold", date: "2026-03-01", changedBy: "Natthapong Charoenwong", note: "Rent-to-sell conversion completed" },
    ],
    maintenanceLogs: [],
    insurance: { policyNumber: "INS-2023-005", provider: "AXA Insurance", expiryDate: "2026-01-31", annualPremium: 58000 },
    odometerLogs: [{ date: "2024-01-01", reading: 0 }],
  },
  {
    id: "car12", licensePlate: "ฐฐ 2222 กทม", modelId: "m9", brandName: "JAC", modelName: "N-Series", bodyType: "Fridge",
    year: 2024, color: "White", status: "Rented", rfidCard: "RFID-JAC-012",
    currentRenterId: "c4", currentRenterName: "PTT Mobility Co.", currentBookingId: "bk6",
    odometer: 15600, isRentToSell: true,
    statusHistory: [
      { status: "Available", date: "2025-09-01", changedBy: "System" },
      { status: "Rented", date: "2025-11-01", changedBy: "System" },
    ],
    maintenanceLogs: [],
    insurance: { policyNumber: "INS-2024-009", provider: "Dhipaya Insurance", expiryDate: "2026-09-30", annualPremium: 42000 },
    odometerLogs: [{ date: "2025-09-01", reading: 0 }],
  },
];

// ─── Bookings ─────────────────────────────────────────────────────────────────
export const bookings: Booking[] = [
  {
    id: "bk1", companyId: "c1", companyName: "Siam Motors Group",
    renterName: "Natthapong Charoenwong", renterPhone: "081-234-5678", renterEmail: "natthapong@siammotors.co.th",
    carId: "car1", licensePlate: "กก 1234 กทม", modelId: "m1", modelName: "N55 EV", brandName: "JAC",
    status: "Active", contractType: "Rent-to-Sell", durationType: "Monthly",
    pickupDate: "2026-02-01", returnDate: "2027-01-31",
    pickupLocationId: "l1", pickupLocationName: "Sukhumvit Service Center",
    returnLocationId: "l1", returnLocationName: "Sukhumvit Service Center",
    addOns: { portableCharger: true, childSeat: false, extraInsurance: true },
    baseRate: 25000, addOnTotal: 3500, deposit: 30000, vat: 2000, total: 60500,
    approvalSteps: [
      { step: "Submitted", actorName: "Natthapong Charoenwong", timestamp: "2026-01-20 09:15", status: "done" },
      { step: "Manager Approved", actorName: "Thanakorn Pattanapong", timestamp: "2026-01-21 14:30", status: "done" },
      { step: "Admin Approved", actorName: "Natthapong Charoenwong", timestamp: "2026-01-22 10:00", status: "done" },
      { step: "Confirmed", actorName: "System", timestamp: "2026-01-22 10:01", status: "done" },
    ],
    createdAt: "2026-01-20",
  },
  {
    id: "bk2", companyId: "c2", companyName: "Bangkok Fleet Solutions",
    renterName: "Thanakorn Pattanapong", renterPhone: "082-345-6789", renterEmail: "thanakorn@bkkfleet.co.th",
    carId: "car3", licensePlate: "คค 9012 กทม", modelId: "m2", modelName: "T9 EV", brandName: "JAC",
    status: "Active", contractType: "Rent-and-Return", durationType: "Monthly",
    pickupDate: "2026-03-01", returnDate: "2026-05-31",
    pickupLocationId: "l2", pickupLocationName: "Silom Office Hub",
    returnLocationId: "l2", returnLocationName: "Silom Office Hub",
    addOns: { portableCharger: false, childSeat: false, extraInsurance: false },
    baseRate: 38000, addOnTotal: 0, deposit: 40000, vat: 2660, total: 80660,
    approvalSteps: [
      { step: "Submitted", actorName: "Thanakorn Pattanapong", timestamp: "2026-02-20 11:00", status: "done" },
      { step: "Manager Approved", actorName: "Thanakorn Pattanapong", timestamp: "2026-02-21 09:30", status: "done" },
      { step: "Admin Approved", actorName: "Natthapong Charoenwong", timestamp: "2026-02-22 15:00", status: "done" },
      { step: "Confirmed", timestamp: "2026-02-22 15:01", status: "done" },
    ],
    createdAt: "2026-02-20",
  },
  {
    id: "bk3", companyId: "c1", companyName: "Siam Motors Group",
    renterName: "Siriporn Wiriyakul", renterPhone: "083-456-7890", renterEmail: "siriporn@siammotors.co.th",
    carId: "car5", licensePlate: "จจ 7890 กทม", modelId: "m5", modelName: "N-Series", brandName: "JAC",
    status: "Active", contractType: "Rent-to-Sell", durationType: "Yearly",
    pickupDate: "2025-08-01", returnDate: "2026-07-31",
    pickupLocationId: "l5", pickupLocationName: "Rama 9 Headquarters",
    returnLocationId: "l5", returnLocationName: "Rama 9 Headquarters",
    addOns: { portableCharger: true, childSeat: false, extraInsurance: true },
    baseRate: 420000, addOnTotal: 15000, deposit: 40000, vat: 30450, total: 505450,
    approvalSteps: [
      { step: "Submitted", actorName: "Siriporn Wiriyakul", timestamp: "2025-07-15 10:00", status: "done" },
      { step: "Manager Approved", actorName: "Thanakorn Pattanapong", timestamp: "2025-07-16 11:00", status: "done" },
      { step: "Admin Approved", actorName: "Natthapong Charoenwong", timestamp: "2025-07-17 09:00", status: "done" },
      { step: "Confirmed", timestamp: "2025-07-17 09:01", status: "done" },
    ],
    createdAt: "2025-07-15",
  },
  {
    id: "bk4", companyId: "c4", companyName: "PTT Mobility Co.",
    renterName: "Siriporn Wiriyakul", renterPhone: "084-567-8901", renterEmail: "siriporn@pttmobility.co.th",
    carId: "car7", licensePlate: "ชช 5678 กทม", modelId: "m11", modelName: "K7", brandName: "JAC",
    status: "Active", contractType: "Rent-and-Return", durationType: "Monthly",
    pickupDate: "2026-04-01", returnDate: "2026-06-30",
    pickupLocationId: "l4", pickupLocationName: "Don Mueang Station",
    returnLocationId: "l4", returnLocationName: "Don Mueang Station",
    addOns: { portableCharger: false, childSeat: false, extraInsurance: false },
    baseRate: 50000, addOnTotal: 0, deposit: 55000, vat: 3500, total: 108500,
    approvalSteps: [
      { step: "Submitted", actorName: "Siriporn Wiriyakul", timestamp: "2026-03-25 14:00", status: "done" },
      { step: "Manager Approved", actorName: "Thanakorn Pattanapong", timestamp: "2026-03-26 10:00", status: "done" },
      { step: "Admin Approved", actorName: "Natthapong Charoenwong", timestamp: "2026-03-27 09:00", status: "done" },
      { step: "Confirmed", timestamp: "2026-03-27 09:01", status: "done" },
    ],
    createdAt: "2026-03-25",
  },
  {
    id: "bk5", companyId: "c3", companyName: "ThaiBev Logistics",
    renterName: "Ananya Sukhonthamat", renterPhone: "085-678-9012", renterEmail: "ananya@thaibevlogistics.co.th",
    carId: "car9", licensePlate: "ญญ 3456 กทม", modelId: "m3", modelName: "Sunray EV", brandName: "JAC",
    status: "Active", contractType: "Rent-and-Return", durationType: "Monthly",
    pickupDate: "2026-03-15", returnDate: "2026-06-14",
    pickupLocationId: "l3", pickupLocationName: "Ladkrabang Depot",
    returnLocationId: "l3", returnLocationName: "Ladkrabang Depot",
    addOns: { portableCharger: true, childSeat: false, extraInsurance: false },
    baseRate: 28000, addOnTotal: 1500, deposit: 30000, vat: 2065, total: 61565,
    approvalSteps: [
      { step: "Submitted", actorName: "Ananya Sukhonthamat", timestamp: "2026-03-10 09:00", status: "done" },
      { step: "Manager Approved", actorName: "Thanakorn Pattanapong", timestamp: "2026-03-11 11:30", status: "done" },
      { step: "Admin Approved", actorName: "Natthapong Charoenwong", timestamp: "2026-03-12 10:00", status: "done" },
      { step: "Confirmed", timestamp: "2026-03-12 10:01", status: "done" },
    ],
    createdAt: "2026-03-10",
  },
  {
    id: "bk6", companyId: "c4", companyName: "PTT Mobility Co.",
    renterName: "Kittipong Sangsuk", renterPhone: "086-789-0123", renterEmail: "kittipong@pttmobility.co.th",
    carId: "car12", licensePlate: "ฐฐ 2222 กทม", modelId: "m9", modelName: "N-Series", brandName: "JAC",
    status: "Active", contractType: "Rent-to-Sell", durationType: "Monthly",
    pickupDate: "2025-11-01", returnDate: "2026-10-31",
    pickupLocationId: "l5", pickupLocationName: "Rama 9 Headquarters",
    returnLocationId: "l5", returnLocationName: "Rama 9 Headquarters",
    addOns: { portableCharger: false, childSeat: false, extraInsurance: true },
    baseRate: 480000, addOnTotal: 24000, deposit: 45000, vat: 35280, total: 584280,
    approvalSteps: [
      { step: "Submitted", actorName: "Kittipong Sangsuk", timestamp: "2025-10-20 09:00", status: "done" },
      { step: "Manager Approved", actorName: "Thanakorn Pattanapong", timestamp: "2025-10-21 10:00", status: "done" },
      { step: "Admin Approved", actorName: "Natthapong Charoenwong", timestamp: "2025-10-22 09:00", status: "done" },
      { step: "Confirmed", timestamp: "2025-10-22 09:01", status: "done" },
    ],
    createdAt: "2025-10-20",
  },
  {
    id: "bk7", companyId: "c2", companyName: "Bangkok Fleet Solutions",
    renterName: "Thanakorn Pattanapong", renterPhone: "082-345-6789", renterEmail: "thanakorn@bkkfleet.co.th",
    carId: "car2", licensePlate: "ขข 5678 กทม", modelId: "m1", modelName: "N55 EV", brandName: "JAC",
    status: "Pending", contractType: "Rent-and-Return", durationType: "Weekly",
    pickupDate: "2026-05-20", returnDate: "2026-05-27",
    pickupLocationId: "l1", pickupLocationName: "Sukhumvit Service Center",
    returnLocationId: "l2", returnLocationName: "Silom Office Hub",
    addOns: { portableCharger: true, childSeat: false, extraInsurance: false },
    baseRate: 22000, addOnTotal: 700, deposit: 30000, vat: 1589, total: 54289,
    approvalSteps: [
      { step: "Submitted", actorName: "Thanakorn Pattanapong", timestamp: "2026-05-14 16:00", status: "done" },
      { step: "Manager Approved", status: "current" },
      { step: "Admin Approved", status: "pending" },
      { step: "Confirmed", status: "pending" },
    ],
    createdAt: "2026-05-14",
  },
  {
    id: "bk8", companyId: "c4", companyName: "PTT Mobility Co.",
    renterName: "Siriporn Wiriyakul", renterPhone: "084-567-8901", renterEmail: "siriporn@pttmobility.co.th",
    carId: "car6", licensePlate: "ฉฉ 1234 กทม", modelId: "m6", modelName: "N-Series", brandName: "JAC",
    status: "Pending", contractType: "Rent-and-Return", durationType: "Daily",
    pickupDate: "2026-05-22", returnDate: "2026-05-27",
    pickupLocationId: "l4", pickupLocationName: "Don Mueang Station",
    returnLocationId: "l4", returnLocationName: "Don Mueang Station",
    addOns: { portableCharger: false, childSeat: false, extraInsurance: false },
    baseRate: 19000, addOnTotal: 0, deposit: 40000, vat: 1330, total: 60330,
    approvalSteps: [
      { step: "Submitted", actorName: "Siriporn Wiriyakul", timestamp: "2026-05-15 08:30", status: "done" },
      { step: "Manager Approved", status: "current" },
      { step: "Admin Approved", status: "pending" },
      { step: "Confirmed", status: "pending" },
    ],
    createdAt: "2026-05-15",
  },
  {
    id: "bk9", companyId: "c1", companyName: "Siam Motors Group",
    renterName: "Natthapong Charoenwong", renterPhone: "081-234-5678", renterEmail: "natthapong@siammotors.co.th",
    carId: "car10", licensePlate: "ฎฎ 7890 กทม", modelId: "m4", modelName: "M3 EV", brandName: "JAC",
    status: "Completed", contractType: "Rent-and-Return", durationType: "Monthly",
    pickupDate: "2026-01-01", returnDate: "2026-03-31",
    pickupLocationId: "l1", pickupLocationName: "Sukhumvit Service Center",
    returnLocationId: "l1", returnLocationName: "Sukhumvit Service Center",
    addOns: { portableCharger: false, childSeat: false, extraInsurance: false },
    baseRate: 27000, addOnTotal: 0, deposit: 30000, vat: 1890, total: 58890,
    approvalSteps: [
      { step: "Submitted", actorName: "Natthapong Charoenwong", timestamp: "2025-12-20 10:00", status: "done" },
      { step: "Manager Approved", actorName: "Thanakorn Pattanapong", timestamp: "2025-12-21 09:00", status: "done" },
      { step: "Admin Approved", actorName: "Natthapong Charoenwong", timestamp: "2025-12-22 10:00", status: "done" },
      { step: "Confirmed", timestamp: "2025-12-22 10:01", status: "done" },
    ],
    createdAt: "2025-12-20",
  },
  {
    id: "bk10", companyId: "c2", companyName: "Bangkok Fleet Solutions",
    renterName: "Thanakorn Pattanapong", renterPhone: "082-345-6789", renterEmail: "thanakorn@bkkfleet.co.th",
    carId: "car8", licensePlate: "ซซ 9012 กทม", modelId: "m12", modelName: "K3", brandName: "JAC",
    status: "Cancelled", contractType: "Rent-and-Return", durationType: "Daily",
    pickupDate: "2026-04-10", returnDate: "2026-04-15",
    pickupLocationId: "l2", pickupLocationName: "Silom Office Hub",
    returnLocationId: "l2", returnLocationName: "Silom Office Hub",
    addOns: { portableCharger: false, childSeat: false, extraInsurance: false },
    baseRate: 17500, addOnTotal: 0, deposit: 35000, vat: 1225, total: 53725,
    approvalSteps: [
      { step: "Submitted", actorName: "Thanakorn Pattanapong", timestamp: "2026-04-05 11:00", status: "done" },
      { step: "Manager Approved", actorName: "Thanakorn Pattanapong", timestamp: "2026-04-06 09:00", status: "done" },
      { step: "Admin Approved", status: "rejected", reason: "Car unavailable due to emergency maintenance" },
      { step: "Confirmed", status: "pending" },
    ],
    createdAt: "2026-04-05",
    cancellationReason: "Car unavailable due to emergency maintenance",
  },
  {
    id: "bk11", companyId: "c4", companyName: "PTT Mobility Co.",
    renterName: "Kittipong Sangsuk", renterPhone: "086-789-0123", renterEmail: "kittipong@pttmobility.co.th",
    carId: "car8", licensePlate: "ซซ 9012 กทม", modelId: "m12", modelName: "K3", brandName: "JAC",
    status: "Confirmed", contractType: "Rent-and-Return", durationType: "Monthly",
    pickupDate: "2026-05-20", returnDate: "2026-06-19",
    pickupLocationId: "l4", pickupLocationName: "Don Mueang Station",
    returnLocationId: "l4", returnLocationName: "Don Mueang Station",
    addOns: { portableCharger: true, childSeat: false, extraInsurance: false },
    baseRate: 35000, addOnTotal: 500, deposit: 38000, vat: 2485, total: 75985,
    approvalSteps: [
      { step: "Submitted", actorName: "Kittipong Sangsuk", timestamp: "2026-05-10 14:00", status: "done" },
      { step: "Manager Approved", actorName: "Thanakorn Pattanapong", timestamp: "2026-05-11 10:00", status: "done" },
      { step: "Admin Approved", actorName: "Natthapong Charoenwong", timestamp: "2026-05-12 09:00", status: "done" },
      { step: "Confirmed", timestamp: "2026-05-12 09:01", status: "done" },
    ],
    createdAt: "2026-05-10",
    extensionRequest: {
      newReturnDate: "2026-07-19",
      submittedAt: "2026-05-15 10:00",
      status: "Pending",
    },
  },
  {
    id: "bk12", companyId: "c1", companyName: "Siam Motors Group",
    renterName: "Siriporn Wiriyakul", renterPhone: "083-456-7890", renterEmail: "siriporn@siammotors.co.th",
    carId: "car2", licensePlate: "ขข 5678 กทม", modelId: "m1", modelName: "N55 EV", brandName: "JAC",
    status: "Completed", contractType: "Rent-and-Return", durationType: "Weekly",
    pickupDate: "2025-12-01", returnDate: "2025-12-28",
    pickupLocationId: "l5", pickupLocationName: "Rama 9 Headquarters",
    returnLocationId: "l1", returnLocationName: "Sukhumvit Service Center",
    addOns: { portableCharger: false, childSeat: false, extraInsurance: true },
    baseRate: 22000, addOnTotal: 2800, deposit: 30000, vat: 1736, total: 56536,
    approvalSteps: [
      { step: "Submitted", actorName: "Siriporn Wiriyakul", timestamp: "2025-11-25 09:00", status: "done" },
      { step: "Manager Approved", actorName: "Thanakorn Pattanapong", timestamp: "2025-11-26 10:00", status: "done" },
      { step: "Admin Approved", actorName: "Natthapong Charoenwong", timestamp: "2025-11-27 09:00", status: "done" },
      { step: "Confirmed", timestamp: "2025-11-27 09:01", status: "done" },
    ],
    createdAt: "2025-11-25",
  },
];

// ─── Pricing ──────────────────────────────────────────────────────────────────
export const pricingTiers: PricingTier[] = [
  { modelId: "m1",  modelName: "N55 EV",              daily1: 1000, daily3: 900,  daily5: 850,  weekly: 5500,  monthly: 25000, yearly: 250000, rentToSell: 30000, deposit: 30000, addonCharger: 250, addonChildSeat: 150, addonInsurance: 500 },
  { modelId: "m2",  modelName: "T9 EV",               daily1: 1600, daily3: 1450, daily5: 1350, weekly: 9000,  monthly: 38000, yearly: 380000, rentToSell: 46000, deposit: 40000, addonCharger: 250, addonChildSeat: 150, addonInsurance: 700 },
  { modelId: "m3",  modelName: "Sunray EV",           daily1: 1200, daily3: 1050, daily5: 980,  weekly: 6500,  monthly: 28000, yearly: 280000, rentToSell: 33000, deposit: 30000, addonCharger: 250, addonChildSeat: 150, addonInsurance: 550 },
  { modelId: "m4",  modelName: "M3 EV",               daily1: 1100, daily3: 980,  daily5: 920,  weekly: 6000,  monthly: 27000, yearly: 270000, rentToSell: 32000, deposit: 30000, addonCharger: 250, addonChildSeat: 150, addonInsurance: 500 },
  { modelId: "m5",  modelName: "N-Series (Cargo)",    daily1: 1400, daily3: 1250, daily5: 1150, weekly: 8000,  monthly: 35000, yearly: 350000, rentToSell: 42000, deposit: 40000, addonCharger: 250, addonChildSeat: 150, addonInsurance: 600 },
  { modelId: "m6",  modelName: "N-Series (Dump)",     daily1: 1550, daily3: 1380, daily5: 1280, weekly: 8800,  monthly: 38000, yearly: 380000, rentToSell: 46000, deposit: 40000, addonCharger: 250, addonChildSeat: 150, addonInsurance: 650 },
  { modelId: "m7",  modelName: "N-Series (Sweeper)",  daily1: 1650, daily3: 1480, daily5: 1380, weekly: 9500,  monthly: 40000, yearly: 400000, rentToSell: 48000, deposit: 42000, addonCharger: 250, addonChildSeat: 150, addonInsurance: 680 },
  { modelId: "m8",  modelName: "N-Series (Wrecker)",  daily1: 1750, daily3: 1580, daily5: 1480, weekly: 10000, monthly: 42000, yearly: 420000, rentToSell: 50000, deposit: 45000, addonCharger: 250, addonChildSeat: 150, addonInsurance: 700 },
  { modelId: "m9",  modelName: "N-Series (Fridge)",   daily1: 1650, daily3: 1480, daily5: 1380, weekly: 9500,  monthly: 40000, yearly: 400000, rentToSell: 48000, deposit: 42000, addonCharger: 250, addonChildSeat: 150, addonInsurance: 680 },
  { modelId: "m10", modelName: "N-Series (Sewage)",   daily1: 1800, daily3: 1620, daily5: 1520, weekly: 10500, monthly: 43000, yearly: 430000, rentToSell: 52000, deposit: 45000, addonCharger: 250, addonChildSeat: 150, addonInsurance: 720 },
  { modelId: "m11", modelName: "K7",                  daily1: 2000, daily3: 1800, daily5: 1700, weekly: 12000, monthly: 50000, yearly: 500000, rentToSell: 60000, deposit: 55000, addonCharger: 300, addonChildSeat: 150, addonInsurance: 800 },
  { modelId: "m12", modelName: "K3",                  daily1: 1400, daily3: 1250, daily5: 1150, weekly: 8000,  monthly: 35000, yearly: 350000, rentToSell: 42000, deposit: 38000, addonCharger: 250, addonChildSeat: 150, addonInsurance: 600 },
  { modelId: "m13", modelName: "Q7",                  daily1: 2200, daily3: 2000, daily5: 1880, weekly: 13500, monthly: 55000, yearly: 550000, rentToSell: 66000, deposit: 60000, addonCharger: 300, addonChildSeat: 150, addonInsurance: 850 },
  { modelId: "m14", modelName: "X-Series",            daily1: 2600, daily3: 2350, daily5: 2200, weekly: 16000, monthly: 65000, yearly: 650000, rentToSell: 78000, deposit: 70000, addonCharger: 300, addonChildSeat: 150, addonInsurance: 950 },
  { modelId: "m15", modelName: "SPV",                 daily1: 2400, daily3: 2150, daily5: 2000, weekly: 14500, monthly: 60000, yearly: 600000, rentToSell: 72000, deposit: 65000, addonCharger: 300, addonChildSeat: 150, addonInsurance: 900 },
];

// ─── Transactions ─────────────────────────────────────────────────────────────
export const transactions: Transaction[] = [
  { id: "tx1", bookingId: "bk1", companyName: "Siam Motors Group", amount: 60500, type: "Rental Fee", method: "Bank Transfer", status: "Completed", date: "2026-02-01", depositStatus: "Held" },
  { id: "tx2", bookingId: "bk2", companyName: "Bangkok Fleet Solutions", amount: 80660, type: "Rental Fee", method: "PromptPay", status: "Completed", date: "2026-03-01", depositStatus: "Held" },
  { id: "tx3", bookingId: "bk3", companyName: "Siam Motors Group", amount: 505450, type: "Rental Fee", method: "Bank Transfer", status: "Completed", date: "2025-08-01", depositStatus: "Held" },
  { id: "tx4", bookingId: "bk5", companyName: "ThaiBev Logistics", amount: 61565, type: "Rental Fee", method: "Credit Card", status: "Completed", date: "2026-03-15", depositStatus: "Held" },
  { id: "tx5", bookingId: "bk9", companyName: "Siam Motors Group", amount: 58890, type: "Rental Fee", method: "Bank Transfer", status: "Completed", date: "2026-01-01", depositStatus: "Refunded" },
  { id: "tx6", bookingId: "bk10", companyName: "Bangkok Fleet Solutions", amount: 53725, type: "Deposit", method: "PromptPay", status: "Completed", date: "2026-04-05", depositStatus: "Refunded" },
  { id: "tx7", bookingId: "bk12", companyName: "Siam Motors Group", amount: 56536, type: "Rental Fee", method: "Credit Card", status: "Completed", date: "2025-12-01", depositStatus: "Refunded" },
  { id: "tx8", bookingId: "bk4", companyName: "PTT Mobility Co.", amount: 108500, type: "Rental Fee", method: "Bank Transfer", status: "Completed", date: "2026-04-01", depositStatus: "Held" },
  { id: "tx9", bookingId: "bk6", companyName: "PTT Mobility Co.", amount: 584280, type: "Rental Fee", method: "Bank Transfer", status: "Completed", date: "2025-11-01", depositStatus: "Held" },
];

export const chargingCosts: ChargingCost[] = [
  { id: "cc1", carId: "car1", licensePlate: "กก 1234 กทม", date: "2026-05-01", kwh: 55, cost: 385, rfidCard: "RFID-JAC-001" },
  { id: "cc2", carId: "car3", licensePlate: "คค 9012 กทม", date: "2026-05-03", kwh: 72, cost: 504, rfidCard: "RFID-JAC-003" },
  { id: "cc3", carId: "car5", licensePlate: "จจ 7890 กทม", date: "2026-05-05", kwh: 68, cost: 476, rfidCard: "RFID-JAC-005" },
  { id: "cc4", carId: "car7", licensePlate: "ชช 5678 กทม", date: "2026-05-07", kwh: 80, cost: 560, rfidCard: "RFID-JAC-007" },
  { id: "cc5", carId: "car9", licensePlate: "ญญ 3456 กทม", date: "2026-05-08", kwh: 45, cost: 315, rfidCard: "RFID-JAC-009" },
  { id: "cc6", carId: "car12", licensePlate: "ฐฐ 2222 กทม", date: "2026-05-10", kwh: 62, cost: 434, rfidCard: "RFID-JAC-012" },
];

// ─── Invoices ─────────────────────────────────────────────────────────────────
export const invoices: Invoice[] = [
  { id: "inv1", invoiceNumber: "INV-2026-001", bookingId: "bk1", companyName: "Siam Motors Group", amount: 56542, vat: 3958, total: 60500, status: "Paid", date: "2026-02-05" },
  { id: "inv2", invoiceNumber: "INV-2026-002", bookingId: "bk2", companyName: "Bangkok Fleet Solutions", amount: 75383, vat: 5277, total: 80660, status: "Paid", date: "2026-03-05" },
  { id: "inv3", invoiceNumber: "INV-2026-003", bookingId: "bk3", companyName: "Siam Motors Group", amount: 472383, vat: 33067, total: 505450, status: "Paid", date: "2025-08-05" },
  { id: "inv4", invoiceNumber: "INV-2026-004", bookingId: "bk5", companyName: "ThaiBev Logistics", amount: 57537, vat: 4028, total: 61565, status: "Sent", date: "2026-03-18" },
  { id: "inv5", invoiceNumber: "INV-2026-005", bookingId: "bk9", companyName: "Siam Motors Group", amount: 55037, vat: 3853, total: 58890, status: "Paid", date: "2026-01-05" },
  { id: "inv6", invoiceNumber: "INV-2026-006", bookingId: "bk4", companyName: "PTT Mobility Co.", amount: 101402, vat: 7098, total: 108500, status: "Sent", date: "2026-04-05" },
  { id: "inv7", invoiceNumber: "INV-2026-007", bookingId: "bk6", companyName: "PTT Mobility Co.", amount: 546056, vat: 38224, total: 584280, status: "Paid", date: "2025-11-05" },
  { id: "inv8", invoiceNumber: "INV-2026-008", bookingId: "bk12", companyName: "Siam Motors Group", amount: 52837, vat: 3699, total: 56536, status: "Paid", date: "2025-12-05" },
];

// ─── Rent-to-Sell ─────────────────────────────────────────────────────────────
export const rentToSellEntries: RentToSellEntry[] = [
  {
    carId: "car1", licensePlate: "กก 1234 กทม", modelName: "N55 EV", brandName: "JAC",
    companyId: "c1", companyName: "Siam Motors Group", contractStart: "2026-02-01",
    totalPaid: 60500, buyoutAmount: 900000, conversionStatus: "Eligible", bookingId: "bk1",
  },
  {
    carId: "car5", licensePlate: "จจ 7890 กทม", modelName: "N-Series (Cargo)", brandName: "JAC",
    companyId: "c1", companyName: "Siam Motors Group", contractStart: "2025-08-01",
    totalPaid: 505450, buyoutAmount: 1200000, conversionStatus: "Renter Confirmed", bookingId: "bk3",
  },
  {
    carId: "car12", licensePlate: "ฐฐ 2222 กทม", modelName: "N-Series (Fridge)", brandName: "JAC",
    companyId: "c4", companyName: "PTT Mobility Co.", contractStart: "2025-11-01",
    totalPaid: 584280, buyoutAmount: 1350000, conversionStatus: "Admin Confirmed", bookingId: "bk6",
  },
  {
    carId: "car11", licensePlate: "ฏฏ 1111 กทม", modelName: "Q7", brandName: "JAC",
    companyId: "c2", companyName: "Bangkok Fleet Solutions", contractStart: "2024-03-01",
    totalPaid: 1100000, buyoutAmount: 1800000, conversionStatus: "Completed", bookingId: "bk12",
  },
];

// ─── Notifications ────────────────────────────────────────────────────────────
export const notifications: AppNotification[] = [
  { id: "n1", type: "approval", title: "Booking Approved", message: "Your booking BK-007 (JAC K3) has been confirmed.", createdAt: "2026-05-12 09:01", read: false, bookingId: "bk11" },
  { id: "n2", type: "reminder", title: "Return Reminder", message: "Your rental for JAC T9 EV (คค 9012) is due in 16 days on 31 May 2026.", createdAt: "2026-05-14 08:00", read: false, bookingId: "bk2" },
  { id: "n3", type: "invoice", title: "Invoice Ready", message: "Invoice INV-2026-004 for ฿61,565 is ready to download.", createdAt: "2026-03-18 15:00", read: true, bookingId: "bk5" },
  { id: "n4", type: "conversion", title: "Rent-to-Sell Update", message: "Your conversion request for JAC N-Series Cargo (จจ 7890) has been confirmed by admin.", createdAt: "2026-05-10 11:00", read: false, bookingId: "bk3" },
  { id: "n5", type: "rejection", title: "Booking Rejected", message: "Booking BK-010 (JAC K3) was rejected: Car unavailable due to emergency maintenance.", createdAt: "2026-04-07 09:00", read: true, bookingId: "bk10" },
  { id: "n6", type: "contract", title: "Contract Expiry Alert", message: "Your rental contract for JAC Sunray EV (ญญ 3456) expires in 30 days.", createdAt: "2026-05-15 08:00", read: false, bookingId: "bk5" },
];

// ─── Admin Users ──────────────────────────────────────────────────────────────
export const adminUsers: AdminUser[] = [
  { id: "a1", name: "Natthapong Charoenwong", email: "natthapong@evfleet.co.th", role: "Super Admin", createdAt: "2024-01-01" },
  { id: "a2", name: "Thanakorn Pattanapong", email: "thanakorn@evfleet.co.th", role: "Manager", createdAt: "2024-03-15" },
  { id: "a3", name: "Siriporn Wiriyakul", email: "siriporn@evfleet.co.th", role: "Manager", createdAt: "2025-01-10" },
];

// ─── Contracts ────────────────────────────────────────────────────────────────
export const contracts: Contract[] = [
  {
    id: "ct1", companyId: "c1", companyName: "Siam Motors Group",
    contactName: "Natthapong Charoenwong", contactPhone: "081-234-5678", contactEmail: "natthapong@siammotors.co.th",
    contractType: "Rent-to-Sell", durationType: "Yearly",
    startDate: "2026-02-01", endDate: "2027-01-31",
    pickupLocationId: "l1", pickupLocationName: "Sukhumvit Service Center",
    returnLocationId: "l1", returnLocationName: "Sukhumvit Service Center",
    lines: [
      { modelId: "m1", modelName: "N55 EV", brandName: "JAC", assignedCars: [{ carId: "car1", licensePlate: "กก 1234 กทม" }], baseRate: 25000 },
      { modelId: "m5", modelName: "N-Series", bodyType: "Cargo", brandName: "JAC", assignedCars: [{ carId: "car5", licensePlate: "จจ 7890 กทม" }], baseRate: 35000 },
    ],
    addOns: { portableCharger: true, childSeat: false, extraInsurance: true },
    deposit: 70000, vat: 4200, total: 565950,
    status: "Active",
    approvalSteps: [
      { step: "Submitted", actorName: "Natthapong Charoenwong", timestamp: "2026-01-20 09:15", status: "done" },
      { step: "Manager Approved", actorName: "Thanakorn Pattanapong", timestamp: "2026-01-21 14:30", status: "done" },
      { step: "Admin Approved", actorName: "Natthapong Charoenwong", timestamp: "2026-01-22 10:00", status: "done" },
      { step: "Confirmed", actorName: "System", timestamp: "2026-01-22 10:01", status: "done" },
    ],
    createdAt: "2026-01-20",
  },
  {
    id: "ct2", companyId: "c2", companyName: "Bangkok Fleet Solutions",
    contactName: "Thanakorn Pattanapong", contactPhone: "082-345-6789", contactEmail: "thanakorn@bkkfleet.co.th",
    contractType: "Rent-and-Return", durationType: "Monthly",
    startDate: "2026-03-01", endDate: "2026-05-31",
    pickupLocationId: "l2", pickupLocationName: "Silom Office Hub",
    returnLocationId: "l2", returnLocationName: "Silom Office Hub",
    lines: [
      { modelId: "m2", modelName: "T9 EV", brandName: "JAC", assignedCars: [{ carId: "car3", licensePlate: "คค 9012 กทม" }], baseRate: 38000 },
    ],
    addOns: { portableCharger: false, childSeat: false, extraInsurance: false },
    deposit: 40000, vat: 2660, total: 80660,
    status: "Active",
    approvalSteps: [
      { step: "Submitted", actorName: "Thanakorn Pattanapong", timestamp: "2026-02-20 11:00", status: "done" },
      { step: "Manager Approved", actorName: "Thanakorn Pattanapong", timestamp: "2026-02-21 09:30", status: "done" },
      { step: "Admin Approved", actorName: "Natthapong Charoenwong", timestamp: "2026-02-22 15:00", status: "done" },
      { step: "Confirmed", timestamp: "2026-02-22 15:01", status: "done" },
    ],
    createdAt: "2026-02-20",
  },
  {
    id: "ct3", companyId: "c3", companyName: "ThaiBev Logistics",
    contactName: "Ananya Sukhonthamat", contactPhone: "085-678-9012", contactEmail: "ananya@thaibevlogistics.co.th",
    contractType: "Rent-and-Return", durationType: "Monthly",
    startDate: "2026-03-15", endDate: "2026-06-14",
    pickupLocationId: "l3", pickupLocationName: "Ladkrabang Depot",
    returnLocationId: "l3", returnLocationName: "Ladkrabang Depot",
    lines: [
      { modelId: "m3", modelName: "Sunray EV", brandName: "JAC", assignedCars: [{ carId: "car9", licensePlate: "ญญ 3456 กทม" }], baseRate: 28000 },
    ],
    addOns: { portableCharger: true, childSeat: false, extraInsurance: false },
    deposit: 30000, vat: 2065, total: 61565,
    status: "Active",
    approvalSteps: [
      { step: "Submitted", actorName: "Ananya Sukhonthamat", timestamp: "2026-03-10 09:00", status: "done" },
      { step: "Manager Approved", actorName: "Thanakorn Pattanapong", timestamp: "2026-03-11 11:30", status: "done" },
      { step: "Admin Approved", actorName: "Natthapong Charoenwong", timestamp: "2026-03-12 10:00", status: "done" },
      { step: "Confirmed", timestamp: "2026-03-12 10:01", status: "done" },
    ],
    createdAt: "2026-03-10",
  },
  {
    id: "ct4", companyId: "c4", companyName: "PTT Mobility Co.",
    contactName: "Siriporn Wiriyakul", contactPhone: "084-567-8901", contactEmail: "siriporn@pttmobility.co.th",
    contractType: "Rent-to-Sell", durationType: "Yearly",
    startDate: "2025-11-01", endDate: "2026-10-31",
    pickupLocationId: "l5", pickupLocationName: "Rama 9 Headquarters",
    returnLocationId: "l5", returnLocationName: "Rama 9 Headquarters",
    lines: [
      { modelId: "m11", modelName: "K7", brandName: "JAC", assignedCars: [{ carId: "car7", licensePlate: "ชช 5678 กทม" }], baseRate: 50000 },
      { modelId: "m9", modelName: "N-Series", bodyType: "Fridge", brandName: "JAC", assignedCars: [{ carId: "car12", licensePlate: "ฐฐ 2222 กทม" }], baseRate: 40000 },
    ],
    addOns: { portableCharger: false, childSeat: false, extraInsurance: true },
    deposit: 100000, vat: 12600, total: 692780,
    status: "Active",
    approvalSteps: [
      { step: "Submitted", actorName: "Siriporn Wiriyakul", timestamp: "2025-10-20 09:00", status: "done" },
      { step: "Manager Approved", actorName: "Thanakorn Pattanapong", timestamp: "2025-10-21 10:00", status: "done" },
      { step: "Admin Approved", actorName: "Natthapong Charoenwong", timestamp: "2025-10-22 09:00", status: "done" },
      { step: "Confirmed", timestamp: "2025-10-22 09:01", status: "done" },
    ],
    createdAt: "2025-10-20",
  },
  {
    id: "ct5", companyId: "c2", companyName: "Bangkok Fleet Solutions",
    contactName: "Thanakorn Pattanapong", contactPhone: "082-345-6789", contactEmail: "thanakorn@bkkfleet.co.th",
    contractType: "Rent-and-Return", durationType: "Weekly",
    startDate: "2026-05-20", endDate: "2026-05-27",
    pickupLocationId: "l1", pickupLocationName: "Sukhumvit Service Center",
    returnLocationId: "l2", returnLocationName: "Silom Office Hub",
    lines: [
      { modelId: "m1", modelName: "N55 EV", brandName: "JAC", assignedCars: [{ carId: "car2", licensePlate: "ขข 5678 กทม" }], baseRate: 22000 },
    ],
    addOns: { portableCharger: true, childSeat: false, extraInsurance: false },
    deposit: 30000, vat: 1589, total: 54289,
    status: "Pending",
    approvalSteps: [
      { step: "Submitted", actorName: "Thanakorn Pattanapong", timestamp: "2026-05-14 16:00", status: "done" },
      { step: "Manager Approved", status: "current" },
      { step: "Admin Approved", status: "pending" },
      { step: "Confirmed", status: "pending" },
    ],
    createdAt: "2026-05-14",
  },
  {
    id: "ct6", companyId: "c4", companyName: "PTT Mobility Co.",
    contactName: "Siriporn Wiriyakul", contactPhone: "084-567-8901", contactEmail: "siriporn@pttmobility.co.th",
    contractType: "Rent-and-Return", durationType: "Daily",
    startDate: "2026-05-22", endDate: "2026-05-27",
    pickupLocationId: "l4", pickupLocationName: "Don Mueang Station",
    returnLocationId: "l4", returnLocationName: "Don Mueang Station",
    lines: [
      { modelId: "m6", modelName: "N-Series", bodyType: "Dump Truck", brandName: "JAC", assignedCars: [{ carId: "car6", licensePlate: "ฉฉ 1234 กทม" }], baseRate: 19000 },
    ],
    addOns: { portableCharger: false, childSeat: false, extraInsurance: false },
    deposit: 40000, vat: 1330, total: 60330,
    status: "Pending",
    approvalSteps: [
      { step: "Submitted", actorName: "Siriporn Wiriyakul", timestamp: "2026-05-15 08:30", status: "done" },
      { step: "Manager Approved", status: "current" },
      { step: "Admin Approved", status: "pending" },
      { step: "Confirmed", status: "pending" },
    ],
    createdAt: "2026-05-15",
  },
];

// ─── Rent Requests ────────────────────────────────────────────────────────────
export const rentRequests: RentRequest[] = [
  {
    id: "req-001",
    companyName: "Bangkok Fleet Solutions",
    contactName: "Thanakorn Pattanapong",
    contactPhone: "081-234-5678",
    contactEmail: "thanakorn@bfs.co.th",
    requestedModels: [{ modelName: "N55 EV", qty: 2 }, { modelName: "T9 EV", qty: 1 }],
    startDate: "2026-06-01",
    endDate: "2026-08-31",
    contractType: "Rent-and-Return",
    durationType: "Monthly",
    notes: "Need vehicles ready for delivery by June 1.",
    status: "Pending",
    createdAt: "2026-05-14",
    approvalSteps: [
      { step: "Sales Review", status: "done", actorName: "Siriporn W.", timestamp: "2026-05-15 10:00" },
      { step: "Manager Approved", status: "current" },
      { step: "Contract Generated", status: "pending" },
    ],
  },
  {
    id: "req-002",
    companyName: "PTT Mobility Co.",
    contactName: "Siripom Wiriyakul",
    contactPhone: "089-876-5432",
    contactEmail: "siripom@pttmobility.co.th",
    requestedModels: [{ modelName: "N-Series (Cargo)", qty: 3 }],
    startDate: "2026-06-15",
    endDate: "2026-09-14",
    contractType: "Rent-and-Return",
    durationType: "Monthly",
    status: "Pending",
    createdAt: "2026-05-15",
    approvalSteps: [
      { step: "Sales Review", status: "current" },
      { step: "Manager Approved", status: "pending" },
      { step: "Contract Generated", status: "pending" },
    ],
  },
];

// ─── Monthly chart data ────────────────────────────────────────────────────────
export const monthlyChartData = [
  { month: "Dec 25", income: 562086, expense: 92000 },
  { month: "Jan 26", income: 58890,  expense: 78000 },
  { month: "Feb 26", income: 120500, expense: 105000 },
  { month: "Mar 26", income: 650475, expense: 130000 },
  { month: "Apr 26", income: 162225, expense: 88000 },
  { month: "May 26", income: 290000, expense: 115000 },
];

// ─── Telematics ───────────────────────────────────────────────────────────────
export const telematicsVehicles: TelematicsVehicle[] = [
  { carId: "car1",  licensePlate: "กก 1234 กทม", modelName: "N55 EV",        brandName: "JAC", companyId: "c1", lat: 13.756, lng: 100.502, speed: 42,  batteryPct: 78, isCharging: false, ignitionOn: true,  odometer: 18420, lastUpdated: "2026-05-20 14:32" },
  { carId: "car5",  licensePlate: "จจ 7890 กทม", modelName: "N-Series",       brandName: "JAC", companyId: "c1", lat: 13.742, lng: 100.535, speed: 0,   batteryPct: 32, isCharging: true,  ignitionOn: false, odometer: 22310, lastUpdated: "2026-05-20 14:30" },
  { carId: "car3",  licensePlate: "คค 9012 กทม", modelName: "T9 EV",          brandName: "JAC", companyId: "c2", lat: 13.770, lng: 100.513, speed: 61,  batteryPct: 55, isCharging: false, ignitionOn: true,  odometer: 9870,  lastUpdated: "2026-05-20 14:33" },
  { carId: "car9",  licensePlate: "ญญ 3456 กทม", modelName: "Sunray EV",      brandName: "JAC", companyId: "c3", lat: 13.730, lng: 100.748, speed: 0,   batteryPct: 91, isCharging: false, ignitionOn: false, odometer: 6540,  lastUpdated: "2026-05-20 13:55" },
  { carId: "car11", licensePlate: "ฎฎ 5678 กทม", modelName: "N-Series",       brandName: "JAC", companyId: "c1", lat: 13.762, lng: 100.488, speed: 28,  batteryPct: 64, isCharging: false, ignitionOn: true,  odometer: 31200, lastUpdated: "2026-05-20 14:31" },
];

export const tripRecords: TripRecord[] = [
  { id: "tr1", carId: "car1",  date: "2026-05-20", startTime: "08:15", endTime: "09:42", startLocation: "Sukhumvit Depot",   endLocation: "Ladkrabang Industrial",  distanceKm: 32.4, durationMin: 87 },
  { id: "tr2", carId: "car1",  date: "2026-05-19", startTime: "07:50", endTime: "09:10", startLocation: "Sukhumvit Depot",   endLocation: "Bang Na Terminal",       distanceKm: 28.1, durationMin: 80 },
  { id: "tr3", carId: "car1",  date: "2026-05-18", startTime: "08:05", endTime: "10:30", startLocation: "Bang Na Terminal",  endLocation: "Don Mueang Logistics",   distanceKm: 45.7, durationMin: 145 },
  { id: "tr4", carId: "car5",  date: "2026-05-20", startTime: "06:30", endTime: "08:00", startLocation: "Silom Office Hub",  endLocation: "Suvarnabhumi Cargo",     distanceKm: 38.2, durationMin: 90 },
  { id: "tr5", carId: "car5",  date: "2026-05-19", startTime: "07:00", endTime: "08:45", startLocation: "Suvarnabhumi Cargo","endLocation": "Silom Office Hub",     distanceKm: 37.9, durationMin: 105 },
  { id: "tr6", carId: "car11", date: "2026-05-20", startTime: "09:00", endTime: "10:15", startLocation: "Sukhumvit Depot",   endLocation: "Chatuchak Market",       distanceKm: 18.6, durationMin: 75 },
];

export const behaviorEvents: BehaviorEvent[] = [
  { id: "be1",  carId: "car1",  timestamp: "2026-05-20 08:32", type: "Hard Braking",       location: "Sukhumvit Rd, km 18",   severity: "Medium" },
  { id: "be2",  carId: "car1",  timestamp: "2026-05-20 09:05", type: "Speeding",            location: "Chalerm Maha Nakhon",   severity: "High" },
  { id: "be3",  carId: "car1",  timestamp: "2026-05-19 08:15", type: "Rapid Acceleration",  location: "Rama IV Rd",            severity: "Low" },
  { id: "be4",  carId: "car1",  timestamp: "2026-05-19 08:50", type: "Idle",                location: "Bang Na Terminal",      severity: "Low" },
  { id: "be5",  carId: "car5",  timestamp: "2026-05-20 06:45", type: "Hard Braking",        location: "Lat Krabang Rd",        severity: "High" },
  { id: "be6",  carId: "car5",  timestamp: "2026-05-20 07:20", type: "Speeding",            location: "Bangna-Trad Hwy",       severity: "Medium" },
  { id: "be7",  carId: "car5",  timestamp: "2026-05-19 07:30", type: "Idle",                location: "Suvarnabhumi Cargo",    severity: "Low" },
  { id: "be8",  carId: "car11", timestamp: "2026-05-20 09:18", type: "Rapid Acceleration",  location: "Phahon Yothin Rd",      severity: "Medium" },
  { id: "be9",  carId: "car11", timestamp: "2026-05-20 09:40", type: "Hard Braking",        location: "Chatuchak Area",        severity: "Low" },
  { id: "be10", carId: "car3",  timestamp: "2026-05-20 11:00", type: "Speeding",            location: "Vibhavadi Rangsit",     severity: "High" },
];

export const purchaseOffers: PurchaseOffer[] = [
  {
    contractId: "ct1",
    carId: "car1",
    licensePlate: "กก 1234 กทม",
    modelName: "N55 EV",
    buyoutAmount: 280000,
    totalPaid: 420000,
    totalBuyout: 560000,
    offerExpiry: "2026-06-30",
    status: "Available",
  },
];
